clone_folder: C:\M

environment:
  DISABLE_QUALITY_CHECK: true
  PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Git\cmd;C:\Program Files\7-Zip
  DEPLOY_PROVIDER: bintray
  BINTRAY_USER: jeroen
  BINTRAY_TARGET: rtools-extra
  BINTRAY_PACKAGE: extra
  PACMAN_REPOSITORY: rtools-extra
  BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)
  matrix:
    - MSYS_VERSION: msys32
      BINTRAY_REPOSITORY: i686
      RTOOLS_ARCH: i686
    - MSYS_VERSION: msys64
      BINTRAY_REPOSITORY: x86_64
      RTOOLS_ARCH: x86_64

matrix:
  fast_finish: true

install:
    - ps: Import-Module .\scripts.ps1
    - ps: InstallRtools

build_script:
#  - C:\%MSYS_VERSION%\usr\bin\bash.exe --login -c exit
#  - C:\%MSYS_VERSION%\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - xcopy /y dummy.conf C:\rtools40\etc\pacman.conf
  - C:\rtools40\usr\bin\pacman --noconfirm -Syyu
  - C:\rtools40\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh"

test: off

artifacts:
  - path: artifacts\*
    name: binaries
  - path: sourcepkg\*
    name: sources

deploy:
  - provider: BinTray
    username: $(BINTRAY_USER)
    subject: $(BINTRAY_TARGET)
    repo: $(BINTRAY_REPOSITORY)
    package: $(BINTRAY_PACKAGE)
    version: latest
    publish: true
    override: true
    api_key:
      secure: rKoNWcAgUrOM7QLX4cEvA1iKoY2DR4ps/1PRveq7rJknjQjcpKx8xGs42CJPhDwJ
    on:
      branch: master
    artifact: binaries

  - provider: BinTray
    username: $(BINTRAY_USER)
    subject: $(BINTRAY_TARGET)
    repo: sources
    package: $(BINTRAY_PACKAGE)
    version: latest
    publish: true
    override: true
    api_key:
      secure: rKoNWcAgUrOM7QLX4cEvA1iKoY2DR4ps/1PRveq7rJknjQjcpKx8xGs42CJPhDwJ
    on:
      branch: master
    artifact: sources
